apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
spec:
  containers:
    - name: kaniko
      image: mutemath966/tekton:kaniko_baseimage
      args: ["--context=git://github.com/him-ran/leanr-kaniko-HR",
              "--destination=mutemath966/tekton:kaniko"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json